-- MySQL Script generated by MySQL Workbench
-- 10/31/18 12:45:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OpavaTour
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OpavaTour
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OpavaTour` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `OpavaTour` ;

-- -----------------------------------------------------
-- Table `OpavaTour`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OpavaTour`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `role` ENUM('admin', 'editor') NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpavaTour`.`tour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OpavaTour`.`tour` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NOT NULL COMMENT '',
  `author` VARCHAR(45) NOT NULL COMMENT '',
  `published` ENUM('yes', 'no', 'wip') NOT NULL COMMENT '',
  `users_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `users_id`)  COMMENT '',
  UNIQUE INDEX `title_UNIQUE` (`title` ASC)  COMMENT '',
  INDEX `fk_tour_users_idx` (`users_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tour_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `OpavaTour`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpavaTour`.`point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OpavaTour`.`point` (
  `id` INT NOT NULL COMMENT '',
  `order` INT NOT NULL COMMENT '',
  `coordinateE` VARCHAR(20) NOT NULL COMMENT '',
  `coordinateN` VARCHAR(20) NOT NULL COMMENT '',
  `text` LONGTEXT NULL COMMENT '',
  `fotoURL` VARCHAR(100) NULL COMMENT '',
  `tour_id` INT NOT NULL COMMENT '',
  `tour_users_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(80) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `tour_id`, `tour_users_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_point_tour1_idx` (`tour_id` ASC, `tour_users_id` ASC)  COMMENT '',
  CONSTRAINT `fk_point_tour1`
    FOREIGN KEY (`tour_id` , `tour_users_id`)
    REFERENCES `OpavaTour`.`tour` (`id` , `users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
